"""Añadir relaciones entre Negocio y Departamento

Revision ID: d60e0e1cc709
Revises: 
Create Date: 2025-12-09 19:02:26.439135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60e0e1cc709'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emprendedores', sa.Column('departamento_residencia_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'emprendedores', 'departamentos', ['departamento_residencia_id'], ['departamento_id'])
    op.add_column('negocios', sa.Column('departamento_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'negocios', 'departamentos', ['departamento_id'], ['departamento_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'negocios', type_='foreignkey')
    op.drop_column('negocios', 'departamento_id')
    op.drop_constraint(None, 'emprendedores', type_='foreignkey')
    op.drop_column('emprendedores', 'departamento_residencia_id')
    # ### end Alembic commands ###
